#!/bin/bash

# prepare any message you want
login_ip="$(echo $SSH_CONNECTION | cut -d " " -f 1)"
login_date="$(date)"
login_name="$(whoami)"
hostName="$(hostname)"
easternTimeZone="$(TZ=America/New_York date)"
# For new line I use $'\n' here
message="New login to server ($hostName)"$'\n'"$login_name"$'\n'"$login_ip"$'\n'"$login_date"$'\n'"$easternTimeZone"

#send it to telegram
sendTelegramMessage "$message"
